name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create-release:
    env:
      GH_TOKEN: ${{ github.token }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract App Version
        run: echo "VERSION=$(grep 'app.version=' gradle.properties | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Create Release
        run: gh release create v${{ env.VERSION }} --generate-notes

  build:
    env:
      GH_TOKEN: ${{ github.token }}

    needs: create-release

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@4.5.0
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Build ${{ matrix.os }}
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Upload Linux Artifact
        if: matrix.os == 'ubuntu-latest'
        run: gh release upload v${{ env.VERSION }} build/compose/binaries/main-release/msi/TextExplorer-${{ env.VERSION }}.msi --clobber

      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        run: gh release upload v${{ env.VERSION }} build/compose/binaries/main-release/deb/TextExplorer-${{ env.VERSION }}.deb --clobber

      - name: Upload macOS Artifact
        if: matrix.os == 'macos-latest'
        run: gh release upload v${{ env.VERSION }} build/compose/binaries/main-release/dmg/TextExplorer-${{ env.VERSION }}.Dmg --clobber